### ISSUE TITLE
v3.44.0 requires Normalizer class, but composer.json does not require ext-intl.

### ISSUE THREAD

**Issue by thbley** [PHP-CS-Fixer/PHP-CS-Fixer#7641]
## Bug report

v3.44.0 requires Normalizer class, but composer.json does not require ext-intl.
No error with v3.43.0.
Installing intl extension or requiring symfony/polyfill-intl-normalizer fixes the problem.

### Description

```
HP CS Fixer 3.44.0 Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.14
Loaded config default from "phpcsfixer.conf".
PHP Fatal error:  Uncaught Error: Class "Normalizer" not found in /var/www/tests/vendor/symfony/string/AbstractUnicodeString.php:31
Stack trace:
#0 /var/www/tests/vendor/symfony/console/Helper/ProgressBar.php(405): Symfony\Component\Console\Helper\Helper::width('70')
#1 /var/www/tests/vendor/symfony/console/Helper/ProgressBar.php(77): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps(70)
#2 /var/www/tests/vendor/friendsofphp/php-cs-fixer/src/Console/Output/Progress/PercentageBarOutput.php(37): Symfony\Component\Console\Helper\ProgressBar->__construct(Object(Symfony\Component\Console\Output\StreamOutput), 70)
#3 /var/www/tests/vendor/friendsofphp/php-cs-fixer/src/Console/Output/Progress/ProgressOutputFactory.php(48): PhpCsFixer\Console\Output\Progress\PercentageBarOutput->__construct(Object(PhpCsFixer\Console\Output\OutputContext))
#4 /var/www/tests/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php(279): PhpCsFixer\Console\Output\Progress\ProgressOutputFactory->create('bar', Object(PhpCsFixer\Console\Output\OutputContext))
#5 /var/www/tests/vendor/symfony/console/Command/Command.php(326): PhpCsFixer\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/tests/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/tests/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(PhpCsFixer\Console\Command\FixCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/tests/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php(92): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/tests/vendor/symfony/console/Application.php(175): PhpCsFixer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/tests/vendor/friendsofphp/php-cs-fixer/php-cs-fixer(102): Symfony\Component\Console\Application->run()
#11 /var/www/tests/vendor/bin/php-cs-fixer(119): include('/var/www/tests/...')
#12 {main}
  thrown in /var/www/tests/vendor/symfony/string/AbstractUnicodeString.php on line 31
```

### Runtime version

v3.44.0

### Used command

```
vendor/bin/php-cs-fixer fix --verbose --dry-run --diff --config phpcsfixer.conf
```

### Configuration file

```
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->exclude('data')
    ->in(__DIR__ . '/');

return (new PhpCsFixer\Config())
    ->setRules([
        '@PhpCsFixer' => true,
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one'],
        'linebreak_after_opening_tag' => true,
        'multiline_whitespace_before_semicolons' => false,
        'not_operator_with_successor_space' => false,
        'phpdoc_summary' => false,
        'php_unit_internal_class' => false,
        'echo_tag_syntax' => ['format' => 'short'],
        'phpdoc_align' => false,
        'php_unit_test_class_requires_covers' => false,
        'return_type_declaration' => ['space_before' => 'none'],
        'yoda_style' => false,
        'types_spaces' => ['space' => 'none'],
        'method_argument_space' => ['keep_multiple_spaces_after_comma' => false, 'on_multiline' => 'ignore'],
        'phpdoc_types_order' => ['sort_algorithm' => 'none'],
        'global_namespace_import' => ['import_classes' => true],
        'increment_style' => ['style' => 'post'],
        'phpdoc_to_comment' => ['ignored_tags' => ['psalm-var']],
        'ordered_types' => ['sort_algorithm' => 'none'],
    ])
    ->setUsingCache(false)
    ->setFinder($finder);
```

### Dockerfile snippet that reproduces the problem

```
FROM alpine:3.19

RUN apk --no-cache upgrade \
    && apk --no-cache add php82-fpm php82-curl php82-pdo_mysql php82-pdo_pgsql php82-mbstring php82-opcache \
        php82-phar php82-tokenizer php82-dom php82-simplexml php82-xml php82-xmlwriter php82-ctype \
    && mv /usr/bin/php82 /usr/bin/php \
    && wget -O /usr/bin/composer https://github.com/composer/composer/releases/latest/download/composer.phar \
    && chmod +x /usr/bin/composer
```

### Dockerfile snippet that fixes the problem

```
FROM alpine:3.19

RUN apk --no-cache upgrade \
    && apk --no-cache add php82-fpm php82-curl php82-pdo_mysql php82-pdo_pgsql php82-mbstring php82-opcache \
        php82-phar php82-tokenizer php82-dom php82-simplexml php82-xml php82-xmlwriter php82-ctype \
        php82-intl \
    && mv /usr/bin/php82 /usr/bin/php \
    && wget -O /usr/bin/composer https://github.com/composer/composer/releases/latest/download/composer.phar \
    && chmod +x /usr/bin/composer
```

**Comment by keradus** [comment]
I wonder if this shouldn't go directly to `symfony/string`, especially exception is raised on their codebase.

Also, how do you install the Fixer package? I installed it manually (without docker) and polyfill is present.

```
ker@d /tmp/test λ composer init --name=test/test --require=friendsofphp/php-cs-fixer:3.44.0 --no-interaction && composer update -q
Writing ./composer.json


ker@d /tmp/test λ ./vendor/bin/php-cs-fixer --version                                                                             
PHP CS Fixer 3.44.0 Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.3.1


ker@d /tmp/test λ composer info symfony/polyfill-intl-normalizer                                                                  
name     : symfony/polyfill-intl-normalizer
descrip. : Symfony polyfill for intl's Normalizer class and related functions
keywords : compatibility, intl, normalizer, polyfill, portable, shim
versions : * v1.28.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/polyfill-intl-normalizer.git 8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92
dist     : [zip] https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92 8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92
path     : /private/tmp/test/vendor/symfony/polyfill-intl-normalizer
names    : symfony/polyfill-intl-normalizer

support
source : https://github.com/symfony/polyfill-intl-normalizer/tree/v1.28.0

autoload
files
psr-4
Symfony\Polyfill\Intl\Normalizer\ => .
classmap
Resources/stubs

requires
php >=7.1

suggests
ext-intl For best performance
```

**Comment by thbley** [comment]
Seems I had the polyfill disabled without installing intl, but that's more a composer topic.
